// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldnRWMPNvPaH7y2yc1RObrAPETYC6C1o',
    appId: '1:397748947217:web:3815643152b67cd86624b0',
    messagingSenderId: '397748947217',
    projectId: 'goactive-a1396',
    authDomain: 'goactive-a1396.firebaseapp.com',
    storageBucket: 'goactive-a1396.appspot.com',
    measurementId: 'G-S5NNH5F209',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt2TsgdcOu71YnUZNz5BW-2R12fvE_tVs',
    appId: '1:397748947217:android:57e734eb2804a4c16624b0',
    messagingSenderId: '397748947217',
    projectId: 'goactive-a1396',
    storageBucket: 'goactive-a1396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeVy8Be91gzYrN-2gvc-EJonbw3ZILeA4',
    appId: '1:397748947217:ios:57449fe76545ba456624b0',
    messagingSenderId: '397748947217',
    projectId: 'goactive-a1396',
    storageBucket: 'goactive-a1396.appspot.com',
    iosClientId: '397748947217-q1vnnd4meclhi9i0dn6434pcvm9713pc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessUiKit',
  );
}
